[project]
name = "makoview"
version = "0.2.0"
description = "Visualise the results from Mako"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.5.1",
    "fastapi>=0.135.2",
    "pydantic>=2",
    "pyfaidx>=0.9.0.4",
    "uvicorn[standard]>=0.42.0",
]

[project.scripts]
makoview-v2 = "makoview.main:cli"

[tool.uv]
package = true

[tool.hatch.build]
artifacts = ["backend/makoview/static"]

[tool.hatch.build.targets.wheel]
packages = ["backend/makoview"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
